public class Bodega{
    public static void main(String[] args){
        System.out.println(""" 
        ......................................+o:.......................................................................
..........................dyso/.....sNMMyshdddhs/...............................................................
..........................ysshdho:-dMMMMMMMMMMNNmh..............................................................
...........................ysNMNyhNMMMMMMMMMMMMMMNdo-...........................................................
..............so/..........-hMMMmNMMMMMMMMMMMMMMMMMMNh:.........................................................
..............dssy+-...-o:.:NMMMMMMMMMMMMMMMMMMMMMMMMMNs........................................................
..............hssssys/-yMmsNMMMMMMMMMMMMMMMMMMMMMMMMMNds........................................................
..............+ysshysyymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.......................................................
...............hsssyhyssydmMMMMMMMMMMMMMNmdmNMMMMMMMMNmmd-......................................................
.............../hssssyhysssydMMMMMMMmmddyssssyhmNNMNMm:.........................................................
................oysssssyhyysshNMNNmdssssssssssyyyyhy/-..........................................................
.................+ysssssydhyssymyyyssssssssssssyysssy/..........................................................
..................:sysssssdsssshyyyyssssssssdsyysssssys/.....-/oyys/-...........................................
..............----.oMNdyssyssssyyyssssssssssss-/osyssssyso++sdmmmNNNd/..........................................
..............ymmmmNMMMMNmhysssyysssyysssssssss` .:ossyssyddmNNNmmmNNd/.........................................
...............+NMMMMMMMMmossyyyyyssssssssssssss`   `.ohhhdNNNmNNmmmmmy.........................................
................:mMMMMMMMhoosyyyyyysssyyyyysssssy. `-/oohhdmNNNmmmmmdmd.........................................
.................:NMMMMMMhooosyyyyyyssysssssssysyhsdms:soyyyhdNmmdmmdds.........................................
............./+oo+yMMMMMMdooosssyyyyyyyssssyhhhdmNNNNNdd:.yysyydddddd+..........................................
.............hNMMMMMMMMMNsoooossssyyyyyyyyhdmmmmmmNNNNmdysshsssssyyyyyo:........................................
............../mMMMMMMMMdsooossssssyyyyyhdmNNNNmmmmmNNNdhssssssooshyyssys/-.....................................
...............-dMMMMMMMyssssssssssssssddNNmmNNNNmmddmmddsssssoooshhossssyyo-...................................
.................dMMMMMMyssssssssssyyhydmNNNNmmmNNmddddmdssssssssossy:./oyssyo-.................................
.................-mMMMMMdsyyyssyyyyssyyydmNNNNmddmmmddmmyssssssssssssyo` `:+ysys:...............................
................../MMMMMNdysyyydyssssoosshdmNmmmmddmmmhysssssssosssssssy-    -oyhs:.............................
.............+mNNmdMMMMMyssssssydssossssssshhdmmmdhhysssssssssssssssssssy+     `:shs-...........................
..............+mMMMMMMMMdysssssshysssssssssssssssssssssssssssssssssssssssys`      .+ds-.........................
................+NMMMMMMMdsssssssdssssssssssssssssssssssssssssssssssssssssyy.        /h+........................
.................-hMMMMMMmssssssssdsssssssssssssssssssssssssssssssssssssssssh:         `:/:.....................
...................oMMMMMNNssssssssdyssssssssssssssssssssmsssssssssssssssssssy+           +:....................
................:oyymMMMMMMhssssssssdysssssssssssssssssssmsssssssssssssssssyhyys   :/-``..+o....................
................/yNMMMMMMMMdssssssssshhysssssssssssssssshhsssssssssssssssshhsymMmho:.:o-...-o:..................
..................-omMMMMMMmsssssssshyshhyssssssssssssshdsssssssssssssssssdyshMMMMMMh--s-....+/.................
....................-oNMMMMMNysssssssyhysshhhyyyyyyhhhhhhhhhyyssssssssyysssdsshmNMMMMd.::.....o-................
......................:dMMMMMmssyssssssyhyyysssyyyyyysssssssyyhhhhhyhdysssssssssymMMMd........-s................
....................+shdMMMMMNssyyyysssssssyhhhhhhhhyooosssssssssshodsssyhhhyysssssyyh........-s................
....................+ymMMMMMMNdsyyyyysssssssssssssssooooossssssoooshosyhhyyssyhhyysssys......:o-................
......................-/hMMMMMMyssyyssssssoooooosooooooosssssssossssy--oyyssssssyyyhhyd:::/+y:..................
........................./NMMMMhssysssssssoooooossssoosooooooooossssyy-.-+syyyssyhdhyyyyyyd+o/..................
........................+hNMMMMdsssyyyyssssooooooooooooooooooosssssssyy....-://++/:--://:::s/o+.................
........................+ydNMMMhssssyyyysssoooooooooooosooooosssssssssys:-.................-sos/................
...........................:sNMysssssyyyysssooooooooossssssssssssssssssydyyyo/:.............-o`//...............
.............................:dsssssssysssssoooooossssssssssssssssssssoshdyssyyyo:...........-+`+/..............
..............................ohsssssssssoosooooossssssssssssssssssssoossdmmhyssyyyo:.........-syh/.............
///::::-------..............-ohmyyysssssssssssssssssssssssssssssssssooososmNyddysssyyy/-.......-yyy.............
sssssssssssooooooo++++++++/+hyyhmyyyysssssssssssssssssssssssssssssssoooooomdhmddhsssssyyo........-..............
sssssssssssssssssssssssssssmssshmdhyyyyssysyssssssssssssssssssssssssooooshmyymsshmysssssm/......................
ssssssssssssssssssssssssssyNsssssyhddhhyyyyyssyyysssssssssssssooooooosshdhydmhyyhdddssshdh-.....................
ssssssssssssssssssssssssssmhdhyssssssyhhddhyyyyyyysssssssssssssssssyhhhdyyddysyydhhddysNyyd/....................
+++ooooooooooooooooooooosyNhhdmmhyssssssssyhhddhhyyyysyyyyyhhhddhhhdssyymdyhysysdyssydhyhhhd+...................
.............--------:::yhysssshmmdhyssssssssshdmhyymyyyymyyssdyyyydddhhyyhmhyysyyssyymdssssyh..................
.......................shssssssssydhddhsssssssssshdhmyyyyhhyhhdmddhhdssssssdsyyyhyyhhddhmysssyh-................
....................../dsssssssssssdhshdhssssssssssyhmmhhhdhydyssyhddyssssyhyysysssssdyyhmysssymo...............
......................hsssssssssssssdhssymhsssssssssssyddyyhmhsssssdsyhysssyhyydsssssdsysymyssshmy/.............
.....................:dssssssssssssssdyssshmhssssssssssssdddyhhysshyssshhysssymhhhhssyshssymssssdyys-...........
.....................sysssssssssssssssmsssssdmssssssssssssshdysssyhhhyyyhysssymysyhyssyhydyymssssmssyo..........
.....................msssssssssssssssshdsssssymysssssssssssssdNdsshsssyhmhhhyyhyyyyhsssssmhhddsssdhsssh/........                           +MMm                                           
`/sdmNd:                           +MMy                                           
syyddmMMMMh`                         /MMh        `````             `.``    `-..`    
dN.  .mMMMM/      `/syys/.        .:o+dMN`    -+o+ydddhhy-      `-+osdh-  :dydmmy.  
sMN-  +MMMm-     /mMy..smNh/.   `/m/` `mMy   sh/---NMMMMMo    .ods. oMMMy-Nd  /MMy  
`hMm. oMNh.     /MMo    .yMMNh/`dMN    :Nm-  dMMM/:::::::`   `mNh`  oMMMMyMh  :MMN/ 
/MMdomd/.---`  dMm      `yMMMNyMMM.    yNy  +MMM/           .MM/   sMMMmmMMsomMMmNo
mMMNdhmNNNNd` mMd       -MMMMMMMMy`   oMM:  /dMNy.          /dd::sNMMd--ymMMMNo`hM
yMMo..-mMMMM- yMM.      sMMMNhMMMMs`  -NMm`  `-+yyo++++       `.::syN/`   .-:/-  .+
yMM+   /MMMM- `yNd.   -yMMNs-`/ydMMhsosmmm.       ```''      `-------ds             
mMM+   oMMMm`   :ydooymmy/`     `.---.````              `:ymNds/:/yNM+            
.MMN. `sMMNs`      ``````                                +MMd:`    `mMy            
+MMhsdmds/`                                              +MMh       dMy            
+so++/:.`                                                 `dMMo_____NMo            
 """);
    System.out.println("MENU:");
    System.out.println("1. Cadastrar bebida\n2. Mostrar bebidas\n3. Comprar bebida\n4. Vender bebida");
    System.out.println("5. Cadastrar cliente\n6. Mostrar clientes\n7. Sair");
    }    
}